"""add field filter indexes

Revision ID: 9c71384d0463
Revises: 9274a55878dc
Create Date: 2026-09-29 22:03:42.652020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c71384d0463'
down_revision: Union[str, Sequence[str], None] = '9274a55878dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_field__area_ha'), 'field', ['area_ha'], unique=False)
    op.create_index(op.f('idx_field__created_at'), 'field', ['created_at'], unique=False)
    op.create_index(op.f('idx_field__crop'), 'field', ['crop'], unique=False)
    op.create_index(op.f('idx_field__owner'), 'field', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_field__owner'), table_name='field')
    op.drop_index(op.f('idx_field__crop'), table_name='field')
    op.drop_index(op.f('idx_field__created_at'), table_name='field')
    op.drop_index(op.f('idx_field__area_ha'), table_name='field')
    # ### end Alembic commands ###
