"""add field centroid

Revision ID: a76eb05c755b
Revises: 9c71384d0463
Create Date: 2026-09-30 00:07:15.079091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = 'a76eb05c755b'
down_revision: Union[str, Sequence[str], None] = '9c71384d0463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('centroid', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), sa.Computed('ST_Centroid(geometry)::geography', persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field', 'centroid')
    # ### end Alembic commands ###
